baseurl = "https://deft.work/"
title = "Deft.Work"
languageCode = "es-es"
googleAnalytics = "G-W1B6WTMNFF"
#googleAnalytics = "UA-45115659-1"
disqusShortname = "deft-work"
MetaDataFormat = "toml"
theme = "hugo-lamp"
defaultContentLanguage = 'es'
[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
  [languages.en]
    languageName = "Inglés"
    weight = 2
    [languages.en.params]
        subtitle = "Technology and Lifestyle"
        description = "My logbook"
  [languages.gr]
    languageName = "Griego"
    weight = 3
    [languages.gr.params]
        subtitle = "Τεχνολογία και τρόπος ζωής"
        description = "Το ημερολόγιό μου"
  [languages.cn]
    languageName = "chino"
    weight = 4
    [languages.cn.params]
         subtitle = "科技與生活方式"
         description = "我的日誌"

[params]
  subtitle = "Tecnología y Estilo de Vida"
  author = "Eloy López"
  logo = "/images/deftwork.webp"
  description = "Mi cuaderno de bitácora"
  paginate = 10

  # Social networks
  email = "elswork@gmail.com"
  github = "DeftWork"
  stripe = "elswork"
  dockerhub = "elswork"
  linkedin = "elswork"
  # googleplus = "https://plus.google.com/+EloyL%C3%B3pezelswork"
  twitter = "elswork"
  slack = "3cfWqL8"
  rss = true  # switch to true to enable RSS icon link

  # Publisher
  adsensePublisher = "ca-pub-1290125220388641"    # Required if you want to include Google Adsense
  # adsenseSlot = "XXX"                   # Required slot to display ads
  # adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Deft.Work - Ciencia y Tecnología para el desarrollo Social"
  googleSiteVerification = "google18d3fb607d246ec9"    # Google Webmaster
  # msValidate = "bing_site_verification_code"                  # Bing Webmaster

[markup.goldmark.renderer]
  unsafe= true

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"
    #blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "ES"
  weight = 1
  identifier = "ES"
  url = "/"
[[menu.main]]
  name = "EN"
  weight = 2
  identifier = "EN"
  url = "/en"
[[menu.main]]
  name = "GR"
  weight = 3
  identifier = "GR"
  url = "/gr"
[[menu.main]]
  name = "CN"
  weight = 4
  identifier = "CN"
  url = "/cn"
#[[menu.main]]
#  name = "AMP Project"
#  weight = 2
#  identifier = "amp"
#  url = "/amp/"
#[[menu.main]]
#  name = "Tags"
#  weight = 3
#  identifier = "tags"
#  url = "/tags/"
