baseurl = "https://deft.work/"
title = "Deft.Work"
languageCode = "es-es"
# DefaultContentLanguage = "es"
googleAnalytics = "UA-45115659-1"
disqusShortname = "deft-work"
MetaDataFormat = "toml"
theme = "hugo-lamp"

[params]
  subtitle = "Tecnología y Estilo de Vida"
  author = "Eloy López"
  logo = "/images/yo.jpeg"
  description = "Mi cuaderno de bitácora"
  paginate = 10

  # Social networks
  email = "elswork@gmail.com"
  github = "DeftWork"
  docker = "elswork"
  linkedin = "elswork"
  # googleplus = "https://plus.google.com/+EloyL%C3%B3pezelswork"
  twitter = "elswork"
  rss = true  # switch to true to enable RSS icon link

  # Publisher
  adsensePublisher = "ca-pub-1290125220388641"    # Required if you want to include Google Adsense
  # adsenseSlot = "XXX"                   # Required slot to display ads
  # adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Deft.Work (SEO Version)"
  googleSiteVerification = "google18d3fb607d246ec9"    # Google Webmaster
  # msValidate = "bing_site_verification_code"                  # Bing Webmaster

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"
    #blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Blog"
  weight = 1
  identifier = "blog"
  url = "/post/"
#[[menu.main]]
#  name = "AMP Project"
#  weight = 2
#  identifier = "amp"
#  url = "/amp/"
#[[menu.main]]
#  name = "Tags"
#  weight = 3
#  identifier = "tags"
#  url = "/tags/"
